name: Pages

on:
  push:
    branches:
      - hexo-source # default branch
  workflow_dispatch:
    branches:
      - hexo-source # default branch

jobs:
  pages:
    # perform action if run manually
    if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, 'DEPLOY') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: | 
        echo "posts will be modified while the first time building"
        npm run build
        echo "make sure run the second time build for the final result"
        npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: hexo-pages # deploying branch
          cname: richard.bizcat.xyz
